# -*- coding: utf-8 -*-
"""Colab_1주차.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uf1vIXwggcvVoO6sHMfXVXMXPnFJHlpO
"""

a = 2
b = 3

a + b

a_list = ['사과', '배', '감', '수박']
a_list[0]

a_list.append('딸기')
a_list

a_list = [{'name' : '철수', 'age':15}, {'name':'영희', 'age':25}]
print(a_list)
print(a_list[0]['age'])

def sum(a, b):
  print('결과는?: ')
  return a + b

result = sum(2, 3)
result

def is_adult(age):
  if age > 20:
    print('성인')
  else:
    print('청소년')

is_adult(20)
is_adult(50)

ages = [15, 25, 30, 8, 13]

for age in ages:
  is_adult(age)

!pip install bs4 requests

import requests
from bs4 import BeautifulSoup
from openpyxl import Workbook
from datetime import datetime


def get_news(keyword):
  wb = Workbook()
  sheet = wb.active

  headers = {'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36'}
  data = requests.get(f'https://search.naver.com/search.naver?where=news&ie=utf8&sm=nws_hty&query={keyword}',headers=headers)

  soup = BeautifulSoup(data.text, 'html.parser')

  lis = soup.select('#main_pack > section > div > div.group_news > ul > li')

  a = lis[0].select_one('a.news_tit')

  for li in lis:
    a = li.select_one('a.news_tit')
    row = [a.text, a['href']]
    sheet.append(row)

  today = datetime.today().strftime("%Y-%m-%d")

  wb.save(f"news/{today}_{keyword}.xlsx")
  wb.close()

get_news('삼성전자')