# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W8spPU3fFmRQAeRBo2xbG7qw0EypLPpw
"""

!pip install dart-fss

import dart_fss as dart_fss
import pandas as pd

api_key = 'a673fb9c1fda9bfd0387563204fbba8ea17dca3e'
dart_fss.set_api_key(api_key=api_key)

corp_list = dart_fss.get_corp_list()

corp_list.corps

all = dart_fss.api.filings.get_corp_code()
all[0]

df = pd.DataFrame(all)
df_listed = df[df['stock_code'].notnull()]
df_non_listed = df[df['stock_code'].isnull()]

df_listed.to_excel('상장종목.xlsx')
df_non_listed.to_excel('비상장종목.xlsx')